### ISSUE TITLE
getting random data for average case calculation

### ISSUE THREAD

**Issue by saileshbro** [ashishsubedi/algorithm_labs#1]
When I did the average case I noticed a significant improvement in the time when I passed the data to be searched rather than looking from the array. (for large array size obviously)
What I mean is, instead of this
```python
binary_search(data, data[r])
```
try with this
```python
someRandVar = data[r]
start = time()
binary_search(data, someRandVar)
end = time()
```
though the time difference is in the range of 10^-5 while plotting it can be seen very significantly

**Comment by ashishsubedi** [comment]
Okay, will check it out

**Comment by ashishsubedi** [comment]
I can see the difference but I am not sure. Maybe some optimization is performed by python interpreter in the second case.
